### ISSUE TITLE
Changing CSRF error status code

### ISSUE THREAD

**Issue by amraei** [adonisjs/shield#14]
Shield is sending 403 HTTP status for mismatched CSFR token. As it's conflicting with cases that user is authenticated but does not have the right permissions, I suggest to choose 406 or 412 to avoid this conflict.

I also suggest to add an option in shield config, so it could be configured manually.

```
// shield.js
module.exports = {
    csrf: {
        enable: true,
        methods: ['POST', 'PUT', 'DELETE'],
        errorStatus: 406
  }
}
```

**Comment by thetutlage** [comment]
I believe, `403` is the perfect error code for CSRF failures. If you are looking to override for any specific reason, you can make use of exception handler to set a different status code.

The following code should do the job

```ts
  public handle (error, ctx) {
    if (error.code === 'E_BAD_CSRF_TOKEN') {
      error.status = 406
    }

    return super.handle(error, ctx)
  }

```

**Comment by amraei** [comment]
@thetutlage I don't think so about 403, but adding a config isn't much more straightforward and clear?

**Comment by thetutlage** [comment]
@amraei Sorry for the late reply. I just wanted to do my research before introducing a config value. I see that many framework including [Django](https://docs.djangoproject.com/en/3.1/ref/csrf/) and [Spring](https://docs.spring.io/spring-security/site/docs/3.2.0.CI-SNAPSHOT/reference/html/csrf.html) uses 403.

I agree that it can be debated further, but I suggest using the Exception handler to update to error status at the application level.

**Comment by amraei** [comment]
@thetutlage Thanks for replying. I just handled things using `error.code`. In my case, I have migrated an API server of a small app from Laravel to Adonisjs. So was looking for way to not change anything in front-end. However, did it.

**Comment by thetutlage** [comment]
Yeah, the goal is not to be Laravel compatible. Everyone draws inspiration from somewhere. I remember Taylor drew a lot from the .Net world. 

I will close the issue, since there is no standard HTTP status code for CSRF errors. Many frameworks (as mentioned earlier) uses 403 and for now I would like to stick to it. :)
