### ISSUE TITLE
Disable CSRF Token for all apis routes in adonis 5

### ISSUE THREAD

**Issue by pk4all** [adonisjs/shield#16]
We want to disable CSRF Token for all Apis.
Like This
```javascript

exceptRoutes: [
    '/api/*'
  ]

``` 
Or any other option.

**Comment by thetutlage** [comment]
Added in https://github.com/adonisjs/shield/commit/7335657efc3249ffa432d78577f39d35eeca89c5

**Comment by pk4all** [comment]
@thetutlage Is this available for use?

**Comment by thetutlage** [comment]
Yes, you can define a callback. Needs to be documented though.

```ts
exceptRoutes: ({ request }) => {
  return request.url().includes('/api')
}
```
