### ISSUE TITLE
Axios can't pick xsrf-token because of case sensitivity

### ISSUE THREAD

**Issue by ashokgelal** [adonisjs/shield#22]
## Package version
@adonisjs/shield: v4.0.3

## Node.js and npm version
node: v14.15.3
npm: v6.14.10

## Description:
Axios seems not to be able to read the value of `xsrf-token` because [Axios expects it to be all in uppercase](https://github.com/axios/axios/blob/master/lib/defaults.js#L73) while Adonis sets it all to lowercase.

I got it working by adding the following lines at the top of my `app.js` file on the client side (which confirms that the issue here is only about the case sensitivity)

```js
import axios from 'axios'
axios.defaults.xsrfCookieName = 'xsrf-token'
```

Although it would be nice, I'm not expecting this to be fixed on Adonis side but if this is the expected behavior, I think it should at least be mentioned in the docs for the benefits of users.

**Comment by hkmsadek** [comment]
Hi there, I am getting same issue. Adonis set the csrf as `xsrf-token` where axios expects to be capital letter. How can we solve this from adonis?
