### ISSUE TITLE
sheild is setting csrf as xsrf-token where we need it to be capital letter

### ISSUE THREAD

**Issue by hkmsadek** [adonisjs/shield#27]
Hi, I see one issue already raised and closed, but I am using it now and seeing same problem. csrf in small letter. How can we solve it from adonis' end?

**Comment by thetutlage** [comment]
It's already been fixed here https://github.com/adonisjs/shield/commit/789fd0d3ee156910bb349b95dff7130271e843b0, but not released yet. I suggest using the Axios config in the meanwhile to provide it a smallcase header name.


<img width="816" alt="Screen Shot 2021-04-21 at 7 08 57 PM" src="https://user-images.githubusercontent.com/1706381/115563323-088b1b00-a2d5-11eb-8cd9-aca71f245326.png">

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/shield/pull/23. Waiting release
