### ISSUE TITLE
I have disabled CSP but getting error

### ISSUE THREAD

**Issue by vikrambiwal** [adonisjs/shield#28]
**_Error:_**

`Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-BqsxNhhO4jHj8gy5BHoMkmiBXlQg75Xj3gQCYKG9pfI='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
`

**_config/shield.ts_**
```
export const csp: ShieldConfig['csp'] = {
  enabled: false,
  directives: {
  },
  reportOnly: false,
}
```

**_package.json_**
"@adonisjs/shield": "^7.0.2",

**Comment by thetutlage** [comment]
If CSP is disabled, then it shouldn't be running. Maybe something else inside your app is also enforcing CSP. It will be nice, if you can share a repo that helps reproduce the issue

**Comment by thetutlage** [comment]
Closing since not actionable
