### ISSUE TITLE
"Invalid or expired CSRF token" in HTTP tests

### ISSUE THREAD

**Issue by casperboone** [adonisjs/shield#41]
### Package version

8.1.0

### Describe the bug

When using the `withCsrfToken()` method the CSRF token does not seem to actually get set (correctly).

During the test run the following output is shown:
```
[14:42:06.195] WARN (9766): Invalid or expired CSRF token
    request_id: "i53xqlaaus7ylpclo56moity"
    x-request-id: "i53xqlaaus7ylpclo56moity"
```

It seems like a CSRF token is set in the request headers, but possible it's an invalid one?
<img width="565" alt="image" src="https://github.com/adonisjs/shield/assets/15815208/7aec5071-ac7f-4cc1-8bbf-d793e7833d06">

In the reproduction repo I show a minimal example that shows the issue.

Thank you for looking into this.

### Reproduction repo

https://github.com/casperboone/adonis-csrf-test-bug/commit/02850bd586e42df7f15eabd6028ee476839fc081

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/shield/releases/tag/v8.1.1

Please also consult the updated docs. https://github.com/adonisjs/v6-docs/commit/43ba644919382aa8bf2aec7404204bdef6623067
